language: go
sudo: false
go:
  - 1.13.x
before_install:
  - sudo apt-get update
  - sudo apt-get -y install opencc
  - go get github.com/liuzl/gocc
script:
  - go test -v -race ./...
branches:
  only:
  - master
